Traceback (most recent call last):
  File "/Users/seanmurphey/workspace/python/rare/rare-api-orchestra-outlaws/./manage.py", line 22, in <module>
    main()
  File "/Users/seanmurphey/workspace/python/rare/rare-api-orchestra-outlaws/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/migrations/operations/fields.py", line 104, in database_forwards
    schema_editor.add_field(
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/backends/sqlite3/schema.py", line 330, in add_field
    self._remake_table(model, create_field=field)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/backends/sqlite3/schema.py", line 191, in _remake_table
    self.effective_default(create_field)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 324, in effective_default
    return field.get_db_prep_save(self._effective_default(field), self.connection)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1271, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1266, in get_prep_value
    return self.to_python(value)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1228, in to_python
    parsed = parse_date(value)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/utils/dateparse.py", line 75, in parse_date
    match = date_re.match(value)
TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: publication_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/seanmurphey/workspace/python/rare/rare-api-orchestra-outlaws/./manage.py", line 22, in <module>
    main()
  File "/Users/seanmurphey/workspace/python/rare/rare-api-orchestra-outlaws/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 123, in loaddata
    self.load_label(fixture_label)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 190, in load_label
    obj.save(using=self.using)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/models/base.py", line 845, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/models/base.py", line 899, in _do_update
    return filtered._update(values) > 0
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/seanmurphey/.local/share/virtualenvs/rare-api-orchestra-outlaws-TASr0s89/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: Problem installing fixture '/Users/seanmurphey/workspace/python/rare/rare-api-orchestra-outlaws/rare_api/fixtures/comments.json': Could not load rare_api.Comment(pk=1): no such column: publication_date
